'use strict';

require.config({
    baseUrl: 'extensions',
    paths: {
        "$model": "../scripts/services/$model",
        "TimeTable": "../scripts/services/timetable",
        "ClassMaster": "../scripts/services/classmaster",
        "Path": "../scripts/services/path",
        "MockData": "../scripts/services/mockdata2",
        "Location": "../scripts/services/location",
        "Cache": "../scripts/services/cache",
        "modelTransformer": "../scripts/services/modeltransformer",
        "Uid": "../scripts/services/uid",
        "Departments": "../scripts/services/departments",
        "Groups": "../scripts/services/groups",
        "SchoolInfos": "../scripts/services/schoolinfos",
        "Forms": "../scripts/services/forms",
        "SubjectTypes": "../scripts/services/subjecttypes",
        "profile": "../scripts/services/profile",
        "Students": "../scripts/services/students",
        "Subjects": "../scripts/services/subjects",
        "Users": "../scripts/services/users",
        "Terms": "../scripts/services/terms",
        "settings": "../scripts/services/settings",
        "File": "../scripts/services/file",
        "Lang": "../scripts/services/lang",
        "InsertionError": "../scripts/models/InsertionError",
    }
});

var scripts = [
    "../scripts/models/User",
    "../scripts/models/Student",
    "../scripts/models/Subject",
    "../scripts/models/Department",
    "../scripts/models/Group",
    "../scripts/models/Form",
    "../scripts/models/Settings",
    "../scripts/models/SchoolInfo",
    "../scripts/controllers/loading3Ctrl",
    "../scripts/controllers/menuCtrl",
    "../scripts/controllers/loginCtrl",
    "../scripts/controllers/usersCtrl",
    "../scripts/controllers/subjectsCtrl",
    "../scripts/controllers/studentsCtrl",
    "../scripts/controllers/navtabsCtrl",
    "../scripts/controllers/classmenuCtrl",
    "../scripts/controllers/departmentsCtrl",
    "../scripts/controllers/profileCtrl",
    "../scripts/controllers/groupsCtrl",
    "../scripts/controllers/registrationCtrl",
    "../scripts/controllers/userCtrl",
    "ReportCard/models/ClassCouncil",
    "ReportCard/models/Marksheet",
    "ReportCard/models/Comment",
    "ReportCard/models/Dcard",
    "Finance/models/Fee",
    "Finance/models/Payment",
    "Staffing/models/Salary",
    "Transcript/models/Transcript", 
    "ReportCard/services/marksheets",
    "ReportCard/services/classcouncils",
    "ReportCard/services/dcards",
    "Finance/services/fees",
    "Finance/services/payments",
    "Staffing/services/salarys",
    "Staffing/services/staffs",
    "Transcript/services/transcripts",
    "ReportCard/controllers/classmasterprofileCtrl",
    "ReportCard/controllers/mastersheetCtrl",
    "ReportCard/controllers/marksheetCtrl",
    "ReportCard/controllers/myclassesCtrl",
    "ReportCard/controllers/classcouncilCtrl",
    "ReportCard/controllers/statsCtrl",
    "ReportCard/controllers/reportcardCtrl",
    "Finance/controllers/registrarprofileCtrl",
    "Finance/controllers/feesCtrl",
    "Finance/controllers/balancesheetCtrl",
    "Staffing/controllers/salaryCtrl",
    "Staffing/controllers/staffregistrationCtrl",
    "Transcript/controllers/transcriptCtrl",
    "Reports/controllers/annualreportCtrl",
    "Reports/controllers/enrollmentCtrl",
    "IDCard/controllers/idcardCtrl",
]

require(scripts, function(){
    angular.bootstrap(document, ["SchoolMan"]);
    console.log("Loaded scripts", scripts);
});

